---
# tasks file for zsh

- name: Install zsh via APT
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Check if oh-my-zsh.sh already exists in homedir
  ansible.builtin.stat:
    path: "~/.oh-my-zsh"
  register: _ohmyzshsh

- name: Download and install oh-my-zsh
  when: not _ohmyzshsh.stat.exists
  block:

    - name: Download oh-my-zsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/oh-my-zsh-install.sh
        mode: +x

    - name: Install oh-my-zsh
      ansible.builtin.command: /tmp/oh-my-zsh-install.sh
      register: oh_my_zsh_output
      changed_when: oh_my_zsh_output.rc != 0

    - name: Cleanup oh-my-zsh install script
      ansible.builtin.file:
        path: /tmp/oh-my-zsh-install.sh
        state: absent
